I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 170, in script
    show character1 normal
Exception: Image 'character1' does not accept attributes 'normal'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 170, in script
    show character1 normal
  File "/Applications/renpy-8.1.1-sdk/renpy/ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Applications/renpy-8.1.1-sdk/renpy/ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "/Applications/renpy-8.1.1-sdk/renpy/exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Applications/renpy-8.1.1-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/Applications/renpy-8.1.1-sdk/renpy/display/core.py", line 496, in _duplicate
    args.extraneous()
  File "/Applications/renpy-8.1.1-sdk/renpy/display/core.py", line 359, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'character1' does not accept attributes 'normal'.

macOS-13.4.1-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
test 1.0
Thu Jul 20 11:27:58 2023
